import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} text-primary bg-mobile-pattern md:bg-tablet-pattern lg:bg-desktop-pattern min-h-screen bg-no-repeat`}
      >
        <div className="bg-[#F4F6FA]/75 min-h-screen">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
